### ISSUE TITLE
Refresh Token

### ISSUE THREAD

**Issue by wisespace-io** [P-Card-International-AG/sk-auth0#9]
Hello,

How the refresh token works? We noticed that we are signed out from the APP after expiration time.
So, the refresh method is never called. Do we need to refresh the token ourselves by checking the
expiration time? Calling ensureTokenRefreshed(...)?

**Comment by NicolasSeiler** [comment]
Yes, you have to call `await ensureTokenRefreshed()` before every API call.

**Comment by NicolasSeiler** [comment]
I have now updated the readme to include instructions for refreshing the token and added a convenience function for wrapping a fetch.
